### PR TITLE
Rename file `MIT-LICENSE.txt` to `LICENSE`

### PR DESCRIPTION
**Pull request by mackler**
This is to enable deployment of this project's bower package as a
WebJar.  For background on this pull-request see [Issue 145](https://github.com/jstat/jstat/issues/145).  For information about WebJars see http://www.webjars.org

_N.B._: the contents of the file in question contain no indication that the licensing terms they specify are those of the MIT license, which information currently (before merging) is contained in the file name (though that information is found in the [`package.json`](https://github.com/jstat/jstat/blob/master/package.json#L13) file).

### CODE REVIEW

**Comment by trevnorris** [comment]
Just curious, would simply `LICENSE` work too?

**Comment by mackler** [comment]
> Just curious, would simply LICENSE work too?

According to the error message, yes.  I chose `LICENSE.txt` only because of [a comment in response to the original issue](https://github.com/jstat/jstat/issues/145#issuecomment-118652770).  I'll be happy to update the patch to use `LICENSE` if you prefer.

**Comment by jamescgibson** [comment]
@trevnorris We seem to traditionally support Windows builds as well, which I think is why we have the .txt extension.

**Comment by trevnorris** [comment]
@jamescgibson Technically it has the `.txt` extension because I added it in 2011 and was just on the tail of developing on Windows. ;-)

@mackler From the error line:

> and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md 

dropping the extension shouldn't be an issue. If you wouldn't mind doing that I'll merge it right away. :)

**Comment by mackler** [comment]
> If you wouldn't mind doing that I'll merge it right away.

My pleasure.  Thank you very much.

**Comment by trevnorris** [comment]
Thanks. Landed in 5e884ac5fc.

Released and published 1.3.0 containing this change.

**Comment by mackler** [comment]
For anyone interested, `jstat` now has [its own page on maven central]( http://search.maven.org/#artifactdetails%7Corg.webjars.bower%7Cjstat%7C1.3.0%7Cjar).

Thanks again!

**Comment by trevnorris** [comment]
@mackler Awesome, thanks. Are there any steps I'll need to take for future releases?

**Comment by mackler** [comment]
> Are there any steps I'll need to take for future releases?

I believe it's fully automated from now on.  When a Java programmer (or other maven client) notices there's a new version of `jstat` they want to use, they can initiate the automated deployment process on the [Bower WebJars page](http://www.webjars.org/bower).

**Comment by trevnorris** [comment]
Sounds great. Thanks for setting this up.

**Pull request closed without merging**
