### PR TITLE
Replace new Function() with regular function

### PR DESCRIPTION
**Pull request by budnix**
This PR fixes:
 * The newest version of the `vows` doesn't work with this project so I've locked latest worked version. Now tests pass;
 * **[most important]** I've replaced the `new Function()` expression which violates Content Security Policy ([CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)).

I didn't include `/dist` files because I don't know what is the release flow of this library. If you want this files I can build and include them to this PR.

### CODE REVIEW

**Comment by jandom** [comment]
@trevnorris hi man sorry to bug you – any chance this is getting merged soon? it will allow folks with content security policy to use this package (csp will by default block all "eval")

**Comment by AMBudnik** [comment]
👍

**Comment by jandom** [comment]
@AMBudnik guys, if we fork this repo, could you potentially point toward a custom fork?

**Comment by AMBudnik** [comment]
I've had a discussion with the team and we'd rather create a fork cause then we'd have a 100% control over it, however, it takes more effort (maintaining, pull requests, issues, security updates...). We're already building a new formula engine so or connection to jStat may end.

Maybe @mrwillihog could help us?

**Comment by trevnorris** [comment]
The `new Function` fix landed in 274cb8a. The changes to `package.json` were separated into 75ae412, which is also the [1.8.0](https://github.com/jstat/jstat/releases/tag/1.8.0) release that contains your fix, to also update `uglify-js`. The style changes to the file will be in a separate commit.

**Comment by AMBudnik** [comment]
Glad to see you back in the game @trevnorris 👍

**Pull request closed without merging**
