### PR TITLE
Add median function for beta distribution: beta.median()

### PR DESCRIPTION
**Pull request by akrawitz**
The median function was not yet implemented for the beta distribution.
This adds one using a straightforward implementation based on the
already existing quantile function.

### CODE REVIEW

**Comment by trevnorris** [comment]
Thanks. Can you update with tests, or post values I can use to add the tests myself?

**Comment by akrawitz** [comment]
Tests added. Also fixed issues with failing test for beta.mode().

**Comment by jamescgibson** [comment]
:+1: Looks good to me. Adding documentation and merging.

**Comment by jamescgibson** [comment]
Never mind, documentation was already there. Thanks again for the great PR @akrawitz. 

Landed in e5c4d7bfac2f337539cfab535d310443202724dd.

**Pull request closed without merging**
