### PR TITLE
Fix issue #96 (PDFs return inconsistent values outside of support)

### PR DESCRIPTION
**Pull request by akrawitz**
[Edit] Fixes issue #96. [/Edit]

The probability density function is defined to be 0 outside of the support. Many jStat distributions already took care of this. This fixes the issue for the others (centralF, chisquare, gamma, invgamma,
kumaraswamy, lognormal, pareto).
Note that this is a separate issue from cases where the parameters to the distribution take on values that are not allowed. In those cases the pdf functions should return NaN.

This pull also includes test cases for the pdf()s that have been modified. For those that already had tests, I just added a test for when x is outside the support. For those that didn't have any test cases yet, I added a few various test cases both with x in and out of support.

### CODE REVIEW

**Comment by trevnorris** [comment]
@akrawitz Based on the other pull requests that I've landed, is this one still applicable?

**Comment by akrawitz** [comment]
@trevnorris Yes, this is still applicable. This pull request specifically deals with `pdf()`s that were not returning `0` when the passed `x` value was outside of the distribution's support. I didn't address this in the other pull requests in order to keep those pull requests agnostic about this issue.

**Comment by akrawitz** [comment]
@trevnorris I see that there are conflicts between this pull request and the current master. I can merge in the current jstat/master, resolve the conflicts, and push those changes onto this pull request, if that would be helpful. (At least, I think I can - still learning git & github.)

**Comment by trevnorris** [comment]
@akrawitz Did you open pull requests with a subset of these commits? When I went to merge this it looked like the majority of functionality was already there.

**Comment by akrawitz** [comment]
I think I realize what the confusion is. My apologies.
The actual functionality (changes to `pdf()` functions) is in src/distribution.js in 5c0f610660cc83245c16b212edcb3210a015637f. Those changes are completely unique to this pull. The other changes are tests for that functionality in the *-test.js files.
I suspect the confusing part is that a number of the distributions didn't previously have  *-test.js files. I added those files in this pull with tests for the `pdf()' functions. However, in other pulls where I modified the `cdf()` or `inv()` functions for the same distributions, I added a *-test.js file with tests for those modified functions. So there is overlap between the pulls in the beginning and end of the *-test.js files (e.g. the `require` statements and the `suite.export` statements), but if you look closely, you will see that the "meat" of those changes are different because whereas the other pulls added tests for the `cdf()` or `pdf()` functions, but this pull adds tests for the `pdf()` functions. I often used the same parameter values to test the different functions (pdf, cdf, and inv), so the code looks very similar (but obviously has different correct results).

**Comment by trevnorris** [comment]
I'm at a loss of how to get any non-conflicting changes in. Would you mind opening a new PR with the changes here that you'd like to land?

**Comment by akrawitz** [comment]
I just made a commit to sync this branch up with master, so the merge should be conflict free, and the current file changes should just be those that clearly go with the intent of this PR.

**Comment by trevnorris** [comment]
It was a little difficult to squash and land the changes, but think I got everything.

Landed in 1cdf371357. Tagged and published in 1.4.2.

**Comment by akrawitz** [comment]
Thanks! Sorry for the difficulty. In retrospect, creating separate PRs to address each bug/issue when the changes were in overlapping files was not a good choice. I will try to make it easier in the future.

**Comment by trevnorris** [comment]
No worries. Happy to have someone contributing. :)

**Pull request closed without merging**
