### PR TITLE
Add row-based vector summation.

### PR DESCRIPTION
**Pull request by fbukevin**
When I was converting an algorithm from MATLAB code to JavaScript and introducing jStat, I found that in MATLAB it has an operation that sums up all the elements in each row of a matrix.

For example, given a matrix like this `A = [1 3 2; 4 2 5; 6 1 4]`.
We can get result in 
```
S =

     6   % 1+3+2
    11  % 4+2+5
    11  % 6+1+4
```
by calling `S = sum(A,2)`.
http://www.mathworks.com/help/matlab/ref/sum.html#bupr1fz

I think this feature is helpful, but current library only sums up in column-based order (result in `11 6 11`). So I made it with replicating sum function. 

Maybe it is better to refactor sum with one more parameter to imply doing operation in row-based (like what MATLAB do).

### CODE REVIEW

**Comment by trevnorris** [comment]
Landed in 8fd80b0b. Thanks.

What does the `2` in `sum(A, 2)` mean?

**Comment by fbukevin** [comment]
As MATLAB document said, `S = sum(A,dim) returns the sum along dimension dim. For example, if A is a matrix, then sum(A,2) is a column vector containing the sum of each row`.

**Comment by trevnorris** [comment]
That makes it sound like it supports N-dimensions. That's a bit overkill for this since it only supports 2.

**Comment by JamesJansson** [comment]
Satisfying for the general case is only a tiny step up in complexity and
computation for the benefits of never having to fix the code again.

**Comment by trevnorris** [comment]
What I mean is that implementing a syntax to support N-dimensions wouldn't look appropriate with the rest of the API. I'm willing to break API compatibility when/if jStat ever supports that.

**Comment by JamesJansson** [comment]
I get your point. The issue is that jstat really is one of the most
important mathematical libraries in JavaScript right now. I've used it as
the basis for a fairly detailed mathematical model for my work.

Sorry to be an annoying politician, but is there a pathway to generalised
expansion into all mathematical operations, or will this require a fork
into a generalized project?

**Comment by trevnorris** [comment]
The main issue is that I'm a JS dev. I manage code quality and performance. No background in statistics beyond the basics. The statisticians previously helping me have moved on. If someone stepped up I'm more than happy to continue doing the work making sure it gets in.

**Comment by fbukevin** [comment]
I think the row-based sum is a good concept of manipulating 2-dimension matrix.
I advised to modify sum to fulfill sum up by row with just passing a flag-like parameter because the operation in sum and sumrow are almost identical.

**Comment by JamesJansson** [comment]
I'm not a statistician, but I am a mathematician. Unfortunately I can't be the lead mathematical advisor on this, but we need to get as much help for you as possible on this repo. I have linked to the repo and this conversation below, hopefully we get a few snags.

https://www.reddit.com/r/statistics/comments/3a98kj/wanted_javascript_programmers_with_a_background/

**Comment by jamescgibson** [comment]
I have reached out to my former thesis advisor and some other old professors about finding a dedicated liason. I agree that finding someone with some experience in these sorts of things, even to just guide development, would be great.

**Comment by trevnorris** [comment]
Thank you all much for the support.

**Pull request closed without merging**
