### PR TITLE
add difference of proportions test

### PR DESCRIPTION
**Pull request by smarden1**
adding the difference of proportions test (both one-sided and two-sided version)

### CODE REVIEW

**Comment by jamescgibson** [comment]
:+1: Thanks for the pull request! As far as I can tell this code looks correct - would you object to me adding a couple of test cases? Alternatively, you're welcome to add them as well; happy to walk through the process if need be.

**Comment by smarden1** [comment]
Anytime! Are these tests sufficient or are you looking for something more?

**Comment by jamescgibson** [comment]
This looks great! :+1: Many thanks for the excellent PR!

@trevnorris I've been procrastinating on learning how to do the full merge, is it something I can do? I just rebase to squash the commits and then merge it into master on the command line and add a signed-off-by, correct?

**Comment by smarden1** [comment]
would it be possible to merge this soon? I'd like to use this and I prefer not to fork...

**Comment by jamescgibson** [comment]
Landed in b1afef0a0739e7246f8e58868a0b521625087e6c

@smarden1, apologies for the delay on merging. Sincere thanks for the PR.

@trevnorris, I'm pretty sure I did the merge right, let me know if I didn't.

Cheers!

**Pull request closed without merging**
