### PR TITLE
Add quantile function, triangular.inv(), for triangular distribution

### PR DESCRIPTION
**Pull request by akrawitz**
The triangular distribution did not have a quantile function (inverse
cumulative distribution function) defined. The math is based on
definition #25 on this page
(http://www.math.uah.edu/stat/special/Triangle.html), but I have
converted that definition to be in terms of the a, b, c parameterization
instead of the a, w, p parameterization.

### CODE REVIEW

**Comment by trevnorris** [comment]
Could you please include a test in `test/distribution/triangular-test.js`? If not then please post some input values, and return values, and I'll add the tests. Thanks.

**Comment by akrawitz** [comment]
Tests added.

**Comment by trevnorris** [comment]
@akrawitz Wanted to let you know that I haven't forgotten about you. Just been on the road for work a lot this last month, but should be free starting this coming Monday. :)

**Comment by akrawitz** [comment]
I'll update the branch for this PR to resolve the merge conflicts - hopefully tonight. I'll post again when I've taken care of it.

**Comment by akrawitz** [comment]
Ok, I've updated this branch to the current master, so there should be no merge conflicts now. If you look at the "files changed" you'll see that this PR just adds triangular.inv() to src/distribution.js and tests for it to test/distribution/triangular-test.js

**Comment by trevnorris** [comment]
Thanks. Landed on 6db14886613. Released as 1.4.3.

**Pull request closed without merging**
