### PR TITLE
Limit max dof on studentt pdf

### PR DESCRIPTION
**Pull request by arturaugusto**

### CODE REVIEW

**Comment by jamescgibson** [comment]
Thanks for the patch! 

My experiments with R's dt(x, dof) function suggest that we'll be limiting the accuracy of the function to about 0.0002, which isn't ideal. 

@trevnorris Thoughts? Question of API design... I've been working on implementing a better algorithm for computing dt but it's slow going.

**Comment by trevnorris** [comment]
@jamescgibson Should it be possible to use the slower calculation only where `dot > 300`?

**Comment by jamescgibson** [comment]
@trevnorris I've been trying to use the algorithm that R uses, which isn't slower for any case, just much more complex to implement.

**Comment by arturaugusto** [comment]
Better solution,

Use the beta function instead of gamma to sample studentt pdf:

```javascript
jStat.extend(jStat.studentt, {
  pdf: function pdf(x, dof) {
    return (1/(Math.sqrt(dof) * jStat.betafn(0.5, dof/2))) *
        Math.pow(1 + ((x * x) / dof), -((dof + 1) / 2));
  }})

jStat.studentt.pdf(0,300)
//0.3986099675993844
jStat.studentt.pdf(0,1e9)
//0.3989420111388685

```

**Comment by arturaugusto** [comment]
But, the above solution will still fail for very big dof.

The main problem was that gamma function for big df, gives infinity:
```javascript
jStat.gammafn(343/2)
//9.48336759344112e+307
jStat.gammafn(344/2)
//Infinity
```

**Comment by trevnorris** [comment]
@jamescgibson Will using `betafn()` for `studentt.pdf()` work just as well?

@arturaugusto Have any potential solutions for the `gammafn()` issue? (also, I assume that `gammafn(344/2)` should be `gammafn(344, 2)` ?)

**Comment by arturaugusto** [comment]
I will test it with R's dt. 

I used ```gammafn(344/2)``` to test the limit case of: https://github.com/jstat/jstat/blob/master/src/distribution.js#L565

**Comment by jamescgibson** [comment]
@trevnorris Yep, that's the usual way of implementing the t distribution. I seem to recall it may be less accurate for x very near 0. 

_Numerical Recipes_ builds all of this off of a very, very good gammafn() implementation. If I can find time this weekend I'll go dig into _Numerical Recipes_ and hopefully fix this issue, #121, and #130 in one swoop.

I have some tests ready to go on #138.

**Pull request closed without merging**
