### PR TITLE
Add quantile function for Pareto distribution: pareto.inv()

### PR DESCRIPTION
**Pull request by akrawitz**
The Pareto distribution did not have a quantile function (inverse
cumulative distribution function) defined. The math for this function is
based on the formula qf defined here:
http://www.distributome.org/js/DistributomeDBSearch.xml.php?s=pareto

### CODE REVIEW

**Comment by jamescgibson** [comment]
@akrawitz Would you object to me adding some tests around this function? Greatly appreciate the contribution, just want to maintain our test coverage ratio :)

**Comment by trevnorris** [comment]
@jamescgibson If you'd like to help out with the tests, @akrawitz has opened several more that I'd also like to see test coverage for. Thanks for your help.

**Comment by akrawitz** [comment]
@jamescgibson You are more than welcome to add tests. However, I can also do it myself, now that I realize it needs to be done!

**Comment by akrawitz** [comment]
Tests added.

**Comment by jamescgibson** [comment]
Thanks! Landed in 4a0ee55d45abe84cb8bc31aee9b0bb59b51a874f, I added a bit of documentation.

**Pull request closed without merging**
